/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.merci.apresentacao;

import br.edu.ifnmg.merci.entidade.Usuario;
import br.edu.ifnmg.merci.excessao.ArgumentoInvalidoException;
import br.edu.ifnmg.merci.excessao.CampoObrigatorioException;
import br.edu.ifnmg.merci.excessao.MerciException;
import br.edu.ifnmg.merci.negocio.UsuarioBO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author wff
 */
public class TelaPrincipal extends javax.swing.JFrame {
    String senha;
    String login;
    Usuario usuario = null;
    TelaUsuarios telaUsuarios = null;
    TelaListarUsuario telaListarUsuario = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        mostrarComponentsSemUsuario();
    }
    public void mostrarComponentsComUsuario(){
        txtLogin.setEnabled(false);
        txtSenha.setEnabled(false);
        lblConfirmarSenha.setEnabled(false);
        txtConfirmaSenha.setEnabled(false);
        btnLogoff.setEnabled(true);
        btnLogin.setEnabled(false);
        btnAlterarSenha.setEnabled(true);
        btnConfirmarSenha.setEnabled(false);
        if(usuario.getGrupo().equals("G")){
            mnuItemUsuarios.setEnabled(true);
        }
    }
    public void mostrarComponentsSemUsuario(){
        txtLogin.setEnabled(true);
        txtSenha.setEnabled(true);
        lblConfirmarSenha.setEnabled(false);
        txtConfirmaSenha.setEnabled(false);
        btnLogoff.setEnabled(false);
        btnLogin.setEnabled(true);
        btnAlterarSenha.setEnabled(false);
        btnConfirmarSenha.setEnabled(false);
        mnuItemUsuarios.setEnabled(false);
    }
    public void mostrarComponentesAlterarSenha(){
        txtLogin.setEnabled(false);
        lblSenha.setEnabled(true);
        txtSenha.setEnabled(true);
        txtSenha.setText("");
        lblConfirmarSenha.setEnabled(true);
        txtConfirmaSenha.setEnabled(true);
        btnLogoff.setEnabled(false);
        btnLogin.setEnabled(false);
        btnAlterarSenha.setEnabled(false);
        btnConfirmarSenha.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        btnLogoff = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnAlterarSenha = new javax.swing.JButton();
        btnConfirmarSenha = new javax.swing.JButton();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfirmarSenha = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItemUsuarios = new javax.swing.JMenu();
        mnuItemCadastro = new javax.swing.JMenuItem();
        mnuItemListar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnuItemSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");
        setExtendedState(6);

        jInternalFrame1.setTitle("Tela de Login");
        jInternalFrame1.setVisible(true);

        btnLogoff.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/user_delete.png"))); // NOI18N
        btnLogoff.setText("Logoff");
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/user.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnAlterarSenha.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/key.png"))); // NOI18N
        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });

        btnConfirmarSenha.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnConfirmarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/arrow_refresh.png"))); // NOI18N
        btnConfirmarSenha.setText("Confirmar Senha");
        btnConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarSenhaActionPerformed(evt);
            }
        });

        txtLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLogin.setAlignmentX(6.0F);
        txtLogin.setBorder(null);
        txtLogin.setMaximumSize(new java.awt.Dimension(10, 10));

        txtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha.setAlignmentX(6.0F);
        txtSenha.setBorder(null);
        txtSenha.setMaximumSize(new java.awt.Dimension(10, 10));

        txtConfirmaSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConfirmaSenha.setAlignmentX(6.0F);
        txtConfirmaSenha.setBorder(null);
        txtConfirmaSenha.setMaximumSize(new java.awt.Dimension(10, 10));

        lblLogin.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin.setText("Login:");
        lblLogin.setAlignmentX(6.0F);
        lblLogin.setBorder(null);
        lblLogin.setMaximumSize(new java.awt.Dimension(10, 10));

        lblSenha.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenha.setText("Senha:");
        lblSenha.setAlignmentX(6.0F);
        lblSenha.setBorder(null);
        lblSenha.setMaximumSize(new java.awt.Dimension(10, 10));

        lblConfirmarSenha.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblConfirmarSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConfirmarSenha.setText("Confirmar Senha:");
        lblConfirmarSenha.setAlignmentX(6.0F);
        lblConfirmarSenha.setBorder(null);
        lblConfirmarSenha.setMaximumSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblConfirmarSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(147, 147, 147))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmarSenha)
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogoff, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/application_form_add.png"))); // NOI18N
        jMenu1.setText("Gestão");

        mnuItemUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/group.png"))); // NOI18N
        mnuItemUsuarios.setText("Usuarios");

        mnuItemCadastro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnuItemCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/add.png"))); // NOI18N
        mnuItemCadastro.setText("Cadastro");
        mnuItemCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCadastroActionPerformed(evt);
            }
        });
        mnuItemUsuarios.add(mnuItemCadastro);

        mnuItemListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        mnuItemListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/zoom.png"))); // NOI18N
        mnuItemListar.setText("Listar");
        mnuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemListarActionPerformed(evt);
            }
        });
        mnuItemUsuarios.add(mnuItemListar);

        jMenu1.add(mnuItemUsuarios);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/lorry.png"))); // NOI18N
        jMenuItem2.setText("Fornecedores");
        jMenu1.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/application_edit.png"))); // NOI18N
        jMenuItem4.setText("Pedidos de Compra");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/cart.png"))); // NOI18N
        jMenuItem5.setText("Estoque");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/package.png"))); // NOI18N
        jMenuItem6.setText("Mercadorias");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/textfield_key.png"))); // NOI18N
        jMenuItem7.setText("Abrir Caixa");
        jMenu1.add(jMenuItem7);

        mnuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/monitor_delete.png"))); // NOI18N
        mnuItemSair.setText("Sair");
        mnuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/money.png"))); // NOI18N
        jMenu2.setText("Vendas");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/coins.png"))); // NOI18N
        jMenuItem3.setText("Fechar Caixa");
        jMenu2.add(jMenuItem3);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/page_white_acrobat.png"))); // NOI18N
        jMenuItem8.setText("Relatórios");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/help.png"))); // NOI18N
        jMenu3.setText("Ajuda");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
         try {
            lerDados();
            UsuarioBO usuarioBO = new UsuarioBO();
            usuario = usuarioBO.buscarLoginAndSenha(login, senha);
            exibirMensagemSucesso("Você logou com o usuario: " + usuario.getNome(), "Login usuário");
            mostrarComponentsComUsuario();
        } catch(CampoObrigatorioException coe){
            exibirMensagemErro(coe.getMessage(), "Login usuário");
        } catch(ArgumentoInvalidoException aie){
            exibirMensagemErro(aie.getMessage(), "Login usuário");
        } catch (Exception e) {
            exibirMensagemErro("Erro desconhecido. Entre em contato com o adminstrador.", "Login usuário");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        mostrarComponentesAlterarSenha();
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        int resposta;
        String mensagem = "Deseja sair do sistema ?";
        String titulo = "Sair";
        resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            limparCamposTela();
            mostrarComponentsSemUsuario();
        }
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void btnConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarSenhaActionPerformed
        try{
            int resposta;
            String mensagem = "Confirmar nova senha?";
            String titulo = "Alterar Senha";
            resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                AlterarSenha();
                UsuarioBO usuarioBO= new UsuarioBO();
                usuarioBO.alterarSenha(usuario);
                exibirMensagemSucesso("Senha cadastrada com sucesso!","Alterar Senha");
                mostrarComponentsComUsuario();
            }
        }catch(MerciException me){
            exibirMensagemErro("Erro ao alterar senha, verifique se as senhas correspondem", "Alterar Senha");
        } catch (SQLException ex) {
            exibirMensagemErro("Erro desconhecido! Contate o administrador do sistema", "Alterar Senha");
        }
    }//GEN-LAST:event_btnConfirmarSenhaActionPerformed

    private void mnuItemCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCadastroActionPerformed
        if(telaUsuarios == null){
            telaUsuarios = new TelaUsuarios();
        }
        telaUsuarios.setVisible(true);
        telaUsuarios.toFront();
    }//GEN-LAST:event_mnuItemCadastroActionPerformed

    private void mnuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSairActionPerformed
        int resposta;
        String mensagem = "Deseja sair do sistema ?";
        String titulo = "Sair";
        resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_mnuItemSairActionPerformed

    private void mnuItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemListarActionPerformed
        if(telaListarUsuario == null){
            telaListarUsuario = new TelaListarUsuario();
        }
        telaListarUsuario.toFront();
        telaListarUsuario.setVisible(true);
    }//GEN-LAST:event_mnuItemListarActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    public void exibirMensagemErro(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
    }

    public void exibirMensagemSucesso(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    public void lerDados(){
        String login = txtLogin.getText().trim();
        String senha = txtSenha.getText().trim();
        
        String mensagem = "";
        
        if(login.isEmpty()){
            mensagem = "Campo login é obrigatorio";
        }
        
        if(senha.isEmpty()){
            mensagem = "Campo senha é obrigatório";
        }
        if(mensagem == "" || mensagem == null){
            this.login = login;
            this.senha = senha;
        }else{
            throw new CampoObrigatorioException(mensagem);
        }
    }
    public void AlterarSenha(){
        String novaSenha = txtSenha.getText().trim();
        String confirmaNovaSenha = txtConfirmaSenha.getText().trim();
        if(senha == "" && confirmaNovaSenha == ""){
            throw new CampoObrigatorioException("Prencha os campos vazios!");
        } 
        if(novaSenha.equals(confirmaNovaSenha)){
            this.usuario.setSenha(novaSenha);
        }else{
            throw new CampoObrigatorioException("Senhas nao conferem!");
        }
    }
    public void limparCamposTela(){
        this.txtLogin.setText("");
        this.txtSenha.setText("");
        this.txtConfirmaSenha.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnConfirmarSenha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JMenuItem mnuItemCadastro;
    private javax.swing.JMenuItem mnuItemListar;
    private javax.swing.JMenuItem mnuItemSair;
    private javax.swing.JMenu mnuItemUsuarios;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
