/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.merci.apresentacao;

import br.edu.ifnmg.merci.entidade.Usuario;
import br.edu.ifnmg.merci.excessao.ArgumentoInvalidoException;
import br.edu.ifnmg.merci.excessao.CampoObrigatorioException;
import br.edu.ifnmg.merci.excessao.MerciException;
import br.edu.ifnmg.merci.negocio.UsuarioBO;
import java.awt.event.FocusEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author wff
 */
public class TelaUsuarios extends javax.swing.JFrame {
    Usuario usuario;
    Usuario usuarioEmEdicao = null;
    Usuario usuarioPesquisado = null;
    TelaListarUsuario telaListarUsuario;
    int usuarioAcao;
    /**
     * Creates new form TelaLogin
     */
    public TelaUsuarios() {
        this.telaListarUsuario = null;
        prepararTela();
        this.desabilitarBotoesTela();
        usuario = new Usuario();
        usuarioAcao = 0;
    }
    public TelaUsuarios(TelaListarUsuario telaListarUsuario, Usuario usuario){
        prepararTela();
        this.usuarioEmEdicao = usuario;
        this.telaListarUsuario = telaListarUsuario;
        this.inicializarCamposTela();
        this.habilitarBotoesTela();
        this.usuarioAcao = 1;
    }

    private void prepararTela() {
        try {
            this.initComponents();
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de aluno", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }

    }
    private void desabilitarBotoesTela(){
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnPesquisar.setEnabled(false);
    }
    private void habilitarBotoesTela(){
        if(!txtNome.getText().isEmpty() && !txtLogin.getText().isEmpty() && 
            !txtSenha.getText().isEmpty()){
            btnSalvar.setEnabled(true);
            btnNovo.setEnabled(true);
        }else{
            btnSalvar.setEnabled(false);
            btnNovo.setEnabled(false);
        }
    }
    
    private void validarCamposObrigatorios() {
        if (txtNome.getText().trim().isEmpty()
                || txtLogin.getText().trim().isEmpty()
                || txtSenha.getText().trim().isEmpty()){        
            throw new CampoObrigatorioException();
        }
    }
    private void limparCamposTela(){
        txtNome.setText("");
        txtLogin.setText("");
        txtSenha.setText("");
        btnGrupoUsuarios.clearSelection();
    }
    private void recuperarCamposTela() {
        usuario.setNome(txtNome.getText());
        usuario.setLogin(txtLogin.getText());
        usuario.setSenha(txtSenha.getText());

        if (chbCaixeiro.isSelected()) {
            usuario.setGrupo("C");
        }
        if (chbGerenteEstoque.isSelected()) {
            usuario.setGrupo("GE");
        }
        if (chbGerente.isSelected()){
            usuario.setGrupo("G");
        } 
        if (chbGestorCompras.isSelected()){
            usuario.setGrupo("GC");
        }
    }
    public void inicializarCamposTela(){
        txtNome.setText(usuarioEmEdicao.getNome());
        txtLogin.setText(usuarioEmEdicao.getLogin());
        txtSenha.setText(usuarioEmEdicao.getSenha());
        if(usuarioEmEdicao.getGrupo().equals("C")) {
            chbCaixeiro.setSelected(true);
        }
        if(usuarioEmEdicao.getGrupo().equals("G")) {
            chbGerente.setSelected(true);
        }
        if(usuarioEmEdicao.getGrupo().equals("GE")) {
            chbGerenteEstoque.setSelected(true);
        }
        if (usuarioEmEdicao.getGrupo().equals("GC")){
            chbGestorCompras.setSelected(true);            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupoUsuarios = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblCamposObrigatorios = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        chbGerente = new javax.swing.JCheckBox();
        chbGerenteEstoque = new javax.swing.JCheckBox();
        chbGestorCompras = new javax.swing.JCheckBox();
        chbCaixeiro = new javax.swing.JCheckBox();
        lblNome = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnListarUsuario = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestao de Usuarios");
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(614, 660));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestao de Usuarios"));
        jPanel1.setToolTipText("TelaUsuarios");
        jPanel1.setAutoscrolls(true);

        lblCamposObrigatorios.setForeground(new java.awt.Color(230, 45, 12));
        lblCamposObrigatorios.setText("* Campos Obrigatórios");

        txtLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoginFocusLost(evt);
            }
        });
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/rubbish7 (2)_1.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setAlignmentX(0.5F);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("*Grupo de Usuários"));

        btnGrupoUsuarios.add(chbGerente);
        chbGerente.setText("Gerente");
        chbGerente.setMinimumSize(null);
        chbGerente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                chbGerenteFocusLost(evt);
            }
        });

        btnGrupoUsuarios.add(chbGerenteEstoque);
        chbGerenteEstoque.setText("Gestor de Estoque");
        chbGerenteEstoque.setMinimumSize(null);
        chbGerenteEstoque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                chbGerenteEstoqueFocusLost(evt);
            }
        });

        btnGrupoUsuarios.add(chbGestorCompras);
        chbGestorCompras.setText("Gestor de Compras");
        chbGestorCompras.setMinimumSize(null);
        chbGestorCompras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                chbGestorComprasFocusLost(evt);
            }
        });

        btnGrupoUsuarios.add(chbCaixeiro);
        chbCaixeiro.setText("Caixeiro");
        chbCaixeiro.setMinimumSize(null);
        chbCaixeiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                chbCaixeiroFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbGerenteEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbGestorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbCaixeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(230, 230, 230))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbGestorCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbGerenteEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbCaixeiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblNome.setText("*Nome:");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/1467304636_search.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setAlignmentX(0.5F);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblLogin.setText("*Login:");

        lblSenha.setText("*Senha:");

        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeFocusLost(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/cross79.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.setAlignmentX(0.5F);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/text133_1.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setAlignmentX(0.5F);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/save (2).png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setAlignmentX(0.5F);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnListarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ifnmg/merci/apresentacao/icones/folder265 (1).png"))); // NOI18N
        btnListarUsuario.setText("Listar");
        btnListarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUsuarioActionPerformed(evt);
            }
        });

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogin)
                            .addComponent(lblSenha)
                            .addComponent(lblNome))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCamposObrigatorios)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCamposObrigatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        int resposta;
        String mensagem = "Os dados ja preenchidos serao descartados";
        String titulo = "Cadastrar Novo";
        resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            limparCamposTela();
            txtLogin.setEnabled(true);
        }
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            UsuarioBO usuarioBO = new UsuarioBO();
            this.validarCamposObrigatorios();
            this.recuperarCamposTela();
            if(this.usuarioAcao == 0){
                usuarioBO.criar(usuario);
                JOptionPane.showMessageDialog(this, "Usuario cadastrado com sucesso!", "Cadastro de usuario", JOptionPane.INFORMATION_MESSAGE);
            }
            if(this.usuarioAcao == 1){    
                usuarioBO.atualizarDados(usuario);           
                JOptionPane.showMessageDialog(this, "Cadasdatra atualizado com sucesso!", "Editar de usuario", JOptionPane.INFORMATION_MESSAGE);
            } 
            this.limparCamposTela();
            desabilitarBotoesTela();
        }catch(MerciException m){
            String mensagem = "Erro ao realizar operação:\n" + m.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de aluno", JOptionPane.ERROR_MESSAGE);
        }catch(Exception e){
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Cadastro de usuario", JOptionPane.ERROR_MESSAGE);
        }    
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            UsuarioBO usuarioBO = new UsuarioBO();
            if(txtLogin!= null){ 
                String login = txtLogin.getText();                  
                try {
                    this.usuarioEmEdicao = usuarioBO.buscarLogin(login);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.inicializarCamposTela();
                this.habilitarBotoesTela();
            }
        }catch(ArgumentoInvalidoException aie){
            String mensagem = "\nMensagem de erro:\n" + aie.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Pesquisar Usuarios", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            UsuarioBO usuarioBO = new UsuarioBO();
            String mensagem = "Deseja excluir usuario?";
            String titulo = "Excluir Usuario";
            int resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION) {
                usuarioBO.excluirUsuario(this.usuarioEmEdicao);   
                JOptionPane.showMessageDialog(this, "Usuario excluido com sucesso!", "Excluir Usuario", JOptionPane.INFORMATION_MESSAGE);     
                telaListarUsuario.carregarTabelaUsuarios();
            }
        } catch (SQLException ex) {
            String mensagem = null;
                mensagem += "\nMensagem de erro:\n" + ex.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Excluir Usuario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusLost
        habilitarBotoesTela();
    }//GEN-LAST:event_txtNomeFocusLost

    private void txtLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoginFocusLost
        habilitarBotoesTela();
        if(!txtLogin.getText().isEmpty()){
            btnPesquisar.setEnabled(true);
        }else{
            btnPesquisar.setEnabled(false);
        }
    }//GEN-LAST:event_txtLoginFocusLost

    private void chbGerenteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chbGerenteFocusLost
        habilitarBotoesTela();
    }//GEN-LAST:event_chbGerenteFocusLost

    private void chbGestorComprasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chbGestorComprasFocusLost
        habilitarBotoesTela();
    }//GEN-LAST:event_chbGestorComprasFocusLost

    private void chbGerenteEstoqueFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chbGerenteEstoqueFocusLost
        habilitarBotoesTela();
    }//GEN-LAST:event_chbGerenteEstoqueFocusLost

    private void chbCaixeiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chbCaixeiroFocusLost
        habilitarBotoesTela();
    }//GEN-LAST:event_chbCaixeiroFocusLost

    private void btnListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUsuarioActionPerformed
        String mensagem = "Os dados ja preenchidos serao descartados";
        String titulo = "Listar Usuarios Cadastrados";
        int resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            limparCamposTela();
            if(telaListarUsuario == null){
                telaListarUsuario = new TelaListarUsuario();
            }
            telaListarUsuario.setVisible(true);
            this.dispose();
        }   
    }//GEN-LAST:event_btnListarUsuarioActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        javax.swing.JTextField tfCodigo;
        try{

            javax.swing.text.MaskFormatter
            format_textField = new javax.swing.text.MaskFormatter("********");

            format_textField.setValidCharacters
            ("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789");

            tfCodigo = new javax.swing.JFormattedTextField(format_textField);

        }catch (Exception e){
            String mensagem = null;
                mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "O Login so pode ter 8 caracteres de A-Z, a-z, 0-9 ", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtLoginActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        javax.swing.JTextField tfCodigo;
        try{

            javax.swing.text.MaskFormatter
            format_textField = new javax.swing.text.MaskFormatter("********");

            format_textField.setValidCharacters
            ("AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789");

            tfCodigo = new javax.swing.JFormattedTextField(format_textField);

        }catch (Exception e){
        
        }
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.ButtonGroup btnGrupoUsuarios;
    private javax.swing.JButton btnListarUsuario;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chbCaixeiro;
    private javax.swing.JCheckBox chbGerente;
    private javax.swing.JCheckBox chbGerenteEstoque;
    private javax.swing.JCheckBox chbGestorCompras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCamposObrigatorios;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
